// Seed content for the Fun Friday games.
// Edit this file to customise items / statements before an event.

const AUCTION_ITEMS = [
  {
    no: 1,
    name: '2 hours of uninterrupted Deep Work every day for 1 week',
    why: "Most powerful productivity booster",
  },
  {
    no: 2,
    name: 'Ability to say "No" to 5 meetings without guilt',
    why: 'Protects your time',
  },
  {
    no: 3,
    name: 'Auto-delegation of all low-value repetitive tasks',
    why: 'Frees up your time',
  },
  {
    no: 4,
    name: 'One full day with zero emails or Slack messages',
    why: 'Complete focus day',
  },
  {
    no: 5,
    name: 'Immediate approval for any idea you propose',
    why: 'Removes bureaucracy',
  },
  {
    no: 6,
    name: 'Personal productivity coach for 1 month',
    why: 'Expert guidance',
  },
  {
    no: 7,
    name: 'Remove all notifications from your phone & laptop',
    why: 'Reduces distractions',
  },
  {
    no: 8,
    name: 'Permission to work from anywhere you want for 2 weeks',
    why: 'Better environment',
  },
  {
    no: 9,
    name: '4-day work week (same salary)',
    why: 'Better work-life balance',
  },
  {
    no: 10,
    name: 'Ability to finish your most important project 2 weeks early',
    why: 'Big career boost',
  },
];

const MYTH_STATEMENTS = [
  {
    no: 1,
    text: '3dots and Wizi Technologies are operating as competitors in 2026',
    answer: 'False',
    explanation: '3dots & Wizi Technologies have joined forces in a strategic partnership!',
  },
  {
    no: 2,
    text: 'Working longer hours makes you more productive',
    answer: 'False',
    explanation: 'Productivity drops after 6–7 hours due to fatigue.',
  },
  {
    no: 2,
    text: 'Multitasking helps you get more work done',
    answer: 'False',
    explanation: 'It reduces efficiency by up to 40%.',
  },
  {
    no: 3,
    text: 'Morning people are always more productive',
    answer: 'False',
    explanation: 'Depends on your chronotype (some are night owls).',
  },
  {
    no: 4,
    text: 'Checking email first thing in the morning is good',
    answer: 'False',
    explanation: 'It starts your day in reactive mode.',
  },
  {
    no: 5,
    text: 'Taking breaks reduces productivity',
    answer: 'False',
    explanation: 'Regular breaks (Pomodoro) increase output.',
  },
  {
    no: 6,
    text: 'Being busy = Being productive',
    answer: 'False',
    explanation: 'Busyness is activity. Productivity is impact.',
  },
  {
    no: 7,
    text: 'You need to be perfect before submitting work',
    answer: 'False',
    explanation: 'Done is better than perfect (80/20 rule).',
  },
  {
    no: 8,
    text: 'Team productivity improves with more meetings',
    answer: 'False',
    explanation: 'Too many meetings kill deep work.',
  },
  {
    no: 9,
    text: 'Using to-do lists makes you less productive',
    answer: 'False',
    explanation: 'Good to-do lists (with priorities) help a lot.',
  },
  {
    no: 10,
    text: 'Productivity is only about individual effort',
    answer: 'False',
    explanation: 'Team systems, communication & culture matter more.',
  },
];

const LOGO_ITEMS = [
  // --- EASY LEVEL ---
  {
    no: 1,
    level: 'easy',
    svg: '/logos/apple.svg',
    hint: 'Founded in 1976 by Steve Jobs & Steve Wozniak in a California garage.',
    options: ['IBM', 'Apple', 'Xerox', 'Microsoft'],
    answer: 'Apple',
    explanation: 'Designed by Ronald Wayne in 1976 featuring Sir Isaac Newton sitting under an apple tree!',
  },
  {
    no: 2,
    level: 'easy',
    svg: '/logos/starbucks.svg',
    hint: 'Original 1971 coffee house from Pike Place Market, Seattle.',
    options: ['Starbucks', 'Costa Coffee', 'Dunkin', 'Tim Hortons'],
    answer: 'Starbucks',
    explanation: 'The 1971 original logo featured a brown twin-tailed siren emblem!',
  },
  {
    no: 3,
    level: 'easy',
    svg: '/logos/pepsi.svg',
    hint: 'First crafted as "Brad\'s Drink" in 1893 in North Carolina.',
    options: ['Dr Pepper', 'Coca-Cola', 'Pepsi', '7UP'],
    answer: 'Pepsi',
    explanation: 'Caleb Bradham renamed it Pepsi-Cola in 1898 and used this ornate red script logo!',
  },
  {
    no: 4,
    level: 'easy',
    svg: '/logos/twitter.svg',
    hint: 'Launched as a podcast side-project at Odeo in 2006.',
    options: ['Tumblr', 'Skype', 'Twitter', 'WhatsApp'],
    answer: 'Twitter',
    explanation: 'Designed by Noah Glass in 2006, the original name was spelled "twttr" with a green slime font!',
  },
  {
    no: 5,
    level: 'easy',
    svg: '/logos/instagram.svg',
    hint: 'Launched by Kevin Systrom & Mike Krieger in October 2010.',
    options: ['Snapchat', 'Instagram', 'Pinterest', 'Flickr'],
    answer: 'Instagram',
    explanation: 'The original 2010 icon was inspired by a vintage retro Polaroid camera!',
  },
  {
    no: 6,
    level: 'easy',
    svg: '/logos/lego.svg',
    hint: 'Danish wooden toy maker founded by Ole Kirk Christiansen in 1932.',
    options: ['Lego', 'Hasbro', 'Mattel', 'Bandai'],
    answer: 'Lego',
    explanation: 'Derived from Danish "leg godt" (play well), this 1936 ink stamp was used on wooden toys!',
  },
  {
    no: 7,
    level: 'easy',
    svg: '/logos/cocacola.svg',
    hint: 'First served at Jacob\'s Pharmacy soda fountain in Atlanta in 1886.',
    options: ['Dr Pepper', 'Coca-Cola', 'Fanta', 'Sprite'],
    answer: 'Coca-Cola',
    explanation: 'Before script lettering was adopted, Coca-Cola used a bold black slab serif font in 1886!',
  },
  {
    no: 8,
    level: 'easy',
    svg: '/logos/mcdonalds.svg',
    hint: 'Drive-in barbecue restaurant founded in San Bernardino, CA in 1940.',
    options: ['Burger King', 'Wendy\'s', 'McDonald\'s', 'Sonic'],
    answer: 'McDonald\'s',
    explanation: 'Speedee the chef was McDonald\'s original winking mascot before Ronald McDonald arrived in 1967!',
  },
  {
    no: 23,
    level: 'easy',
    svg: '/logos/google.svg',
    hint: 'Search engine founded by Larry Page & Sergey Brin at Stanford in 1998.',
    options: ['Yahoo', 'Google', 'Altavista', 'Lycos'],
    answer: 'Google',
    explanation: 'The original 1998 logo featured a 3D GIMP font with a red exclamation point at the end!',
  },
  {
    no: 24,
    level: 'easy',
    svg: '/logos/microsoft.svg',
    hint: 'Software company founded by Bill Gates & Paul Allen in 1975 in Albuquerque.',
    options: ['Apple', 'IBM', 'Microsoft', 'Intel'],
    answer: 'Microsoft',
    explanation: 'The 1975 original logo used a grooved 1970s disco font and was spelled Micro-Soft!',
  },
  {
    no: 25,
    level: 'easy',
    svg: '/logos/nike.svg',
    hint: 'Oregon sportswear brand named after the Greek goddess of victory.',
    options: ['Puma', 'Nike', 'Reebok', 'Asics'],
    answer: 'Nike',
    explanation: 'Graphic design student Carolyn Davidson created the iconic Swoosh logo in 1971 for just $35!',
  },
  {
    no: 26,
    level: 'easy',
    svg: '/logos/kfc.svg',
    hint: 'Fast food chain founded by Harland Sanders in Corbin, Kentucky in 1952.',
    options: ['KFC', 'Popeyes', 'Church\'s', 'Bojangles'],
    answer: 'KFC',
    explanation: 'The original 1952 logo featured Colonel Sanders wearing his signature string tie and glasses!',
  },
  {
    no: 27,
    level: 'easy',
    svg: '/logos/adidas.svg',
    hint: 'German sportswear company founded by Adolf Dassler in Herzogenaurach in 1949.',
    options: ['Puma', 'Adidas', 'Fila', 'Kappa'],
    answer: 'Adidas',
    explanation: 'The 1949 original logo featured a spiked track running shoe suspended between two tall letter ds!',
  },

  // --- MEDIUM LEVEL ---
  {
    no: 9,
    level: 'medium',
    svg: '/logos/shell.svg',
    hint: 'Started as a London import business selling antique sea shells in 1891.',
    options: ['Exxon', 'Chevron', 'Shell', 'BP'],
    answer: 'Shell',
    explanation: 'In 1904 Shell adopted a realistic black & white mussel shell drawing before adopting yellow & red colors!',
  },
  {
    no: 10,
    level: 'medium',
    svg: '/logos/canon.svg',
    hint: 'Japanese optical camera company founded in 1934.',
    options: ['Nikon', 'Canon', 'Olympus', 'Sony'],
    answer: 'Canon',
    explanation: 'Originally named Kwanon after the Buddhist Goddess of Mercy with a thousand arms!',
  },
  {
    no: 11,
    level: 'medium',
    svg: '/logos/ford.svg',
    hint: 'American automaker founded in Detroit, Michigan in 1903.',
    options: ['Chevrolet', 'Ford', 'Chrysler', 'Dodge'],
    answer: 'Ford',
    explanation: 'Henry Ford\'s original 1903 emblem used an ornate Victorian border before the blue oval in 1927!',
  },
  {
    no: 12,
    level: 'medium',
    svg: '/logos/ibm.svg',
    hint: 'Formed from the merger of 3 computing-tabulating-recording companies.',
    options: ['IBM', 'AT&T', 'HP', 'Intel'],
    answer: 'IBM',
    explanation: 'Renamed International Business Machines in 1924, IBM adopted a globe emblem representing world trade!',
  },
  {
    no: 13,
    level: 'medium',
    svg: '/logos/nintendo.svg',
    hint: 'Handcrafted playing card company founded in Kyoto, Japan in 1889.',
    options: ['Sega', 'Nintendo', 'Capcom', 'Bandai'],
    answer: 'Nintendo',
    explanation: 'Fusajiro Yamauchi named it 任天堂 (Nin-ten-do), which roughly translates to "leave luck to heaven"!',
  },
  {
    no: 14,
    level: 'medium',
    svg: '/logos/volkswagen.svg',
    hint: 'German carmaker founded in Wolfsburg in 1937.',
    options: ['BMW', 'Audi', 'Volkswagen', 'Porsche'],
    answer: 'Volkswagen',
    explanation: 'The original 1939 VW emblem surrounded the interlocking V and W with a gear-tooth cog wheel!',
  },
  {
    no: 15,
    level: 'medium',
    svg: '/logos/burgerking.svg',
    hint: 'Founded in Jacksonville, Florida in 1953 as Insta-Burger King.',
    options: ['Burger King', 'Jack in the Box', 'Hardee\'s', 'Carl\'s Jr.'],
    answer: 'Burger King',
    explanation: 'The 1954 original logo featured a cartoon monarch character sitting atop a sunburst backdrop!',
  },
  {
    no: 28,
    level: 'medium',
    svg: '/logos/doritos.svg',
    hint: 'Flavored tortilla chip brand launched nationwide by Frito-Lay in 1966.',
    options: ['Cheetos', 'Doritos', 'Tostitos', 'Pringles'],
    answer: 'Doritos',
    explanation: 'Derived from Spanish "doradito" (little golden thing), the 1966 original logo had a separate colored square box for each letter!',
  },
  {
    no: 29,
    level: 'medium',
    svg: '/logos/pringles.svg',
    hint: 'Stackable potato chip brand developed by Procter & Gamble in 1967.',
    options: ['Lay\'s', 'Pringles', 'Ruffles', 'Lays'],
    answer: 'Pringles',
    explanation: 'Julius Pringles (Mr. P) was created in 1967 featuring a rosy-cheeked head with a black mustache and red bow tie!',
  },
  {
    no: 30,
    level: 'medium',
    svg: '/logos/subway.svg',
    hint: 'Fast food submarine sandwich chain founded in Bridgeport, Connecticut in 1965.',
    options: ['Subway', 'Jimmy John\'s', 'Quiznos', 'Firehouse Subs'],
    answer: 'Subway',
    explanation: 'Originally named Pete\'s Super Submarines in 1965, the 1968 logo introduced the iconic yellow and green text with arrow tips on S and Y!',
  },
  {
    no: 31,
    level: 'medium',
    svg: '/logos/heineken.svg',
    hint: 'Dutch brewing company founded by Gerard Adriaan Heineken in Amsterdam in 1864.',
    options: ['Stella Artois', 'Heineken', 'Carlsberg', 'Beck\'s'],
    answer: 'Heineken',
    explanation: 'The 1884 green oval bottle label introduced the red five-pointed star, representing the 4 elements of brewing plus mystery magic!',
  },
  {
    no: 32,
    level: 'medium',
    svg: '/logos/toyota.svg',
    hint: 'Japanese automaker founded by Kiichiro Toyoda in Aichi Prefecture in 1937.',
    options: ['Honda', 'Nissan', 'Toyota', 'Subaru'],
    answer: 'Toyota',
    explanation: 'The company was originally named Toyoda (トヨダ). In 1936 they changed the name to Toyota (トヨタ) because it required 8 brush strokes, a lucky number in Japan!',
  },

  // --- HARD LEVEL ---
  {
    no: 16,
    level: 'hard',
    svg: '/logos/amazon.svg',
    hint: 'Online bookstore founded by Jeff Bezos in Bellevue, Washington in 1994.',
    options: ['eBay', 'Amazon', 'Overstock', 'Rakuten'],
    answer: 'Amazon',
    explanation: 'The 1995 original logo featured a stylized letter "A" over a silhouette of the Amazon river!',
  },
  {
    no: 17,
    level: 'hard',
    svg: '/logos/mozilla.svg',
    hint: 'Open-source web project created at Netscape Communications in 1998.',
    options: ['Firefox', 'Mozilla', 'Opera', 'Netscape'],
    answer: 'Mozilla',
    explanation: 'Designed by street artist Shepard Fairey, the original 1998 mascot was a roaring red T-Rex dinosaur!',
  },
  {
    no: 18,
    level: 'hard',
    svg: '/logos/nokia.svg',
    hint: 'Founded in 1865 as a single salmon-river wood pulp mill in Finland.',
    options: ['Nokia', 'Ericsson', 'Siemens', 'Motorola'],
    answer: 'Nokia',
    explanation: 'Named after the Nokianvirta river, Nokia\'s 1865 original logo featured a Finnish salmon fish emblem!',
  },
  {
    no: 19,
    level: 'hard',
    svg: '/logos/samsung.svg',
    hint: 'Trading and grocery company founded in Taegu, Korea in 1938.',
    options: ['LG', 'Samsung', 'Hyundai', 'Daewoo'],
    answer: 'Samsung',
    explanation: 'In Korean, "Samsung" means "Three Stars". The 1938 original logo was a grocery stamp with 3 stars!',
  },
  {
    no: 20,
    level: 'hard',
    svg: '/logos/audi.svg',
    hint: 'German luxury car manufacturer founded by August Horch in 1910.',
    options: ['Mercedes-Benz', 'BMW', 'Audi', 'Alfa Romeo'],
    answer: 'Audi',
    explanation: 'Before the 4 interlocked rings, Audi\'s 1910 logo was an inverted black triangle with a numeral 1 on top!',
  },
  {
    no: 21,
    level: 'hard',
    svg: '/logos/bmw.svg',
    hint: 'Evolved from Rapp Motorenwerke aircraft engine manufacturer in 1917.',
    options: ['BMW', 'Volvo', 'Saab', 'Porsche'],
    answer: 'BMW',
    explanation: 'The 1917 original BMW badge retained Rapp\'s outer ring shape with gold lettering and Bavarian flag colors!',
  },
  {
    no: 22,
    level: 'hard',
    svg: '/logos/mazda.svg',
    hint: 'Automotive manufacturer founded in Hiroshima, Japan in 1920.',
    options: ['Subaru', 'Mazda', 'Mitsubishi', 'Suzuki'],
    answer: 'Mazda',
    explanation: 'The 1936 triple-M logo represented the Hiroshima river streams and the initials of Mazda Motor Manufacturer!',
  },
  {
    no: 33,
    level: 'hard',
    svg: '/logos/barbie.svg',
    hint: 'Fashion doll manufactured by American toy company Mattel, launched in 1959.',
    options: ['Bratz', 'Barbie', 'Polly Pocket', 'American Girl'],
    answer: 'Barbie',
    explanation: 'Ruth Handler created Barbie (named after her daughter Barbara) in 1959 with a classic magenta hand-drawn script logo!',
  },
  {
    no: 34,
    level: 'hard',
    svg: '/logos/playstation.svg',
    hint: 'Video game brand created and produced by Sony Computer Entertainment in 1994.',
    options: ['Xbox', 'PlayStation', 'Atari', 'Dreamcast'],
    answer: 'PlayStation',
    explanation: 'Manabu Sakamoto designed the 3D polygon logo in 1994, featuring a red letter P standing vertically over a flat letter S shadow!',
  },
  {
    no: 35,
    level: 'hard',
    svg: '/logos/warnerbros.svg',
    hint: 'American film and entertainment studio founded by four brothers in 1923.',
    options: ['Universal', 'Paramount', 'Warner Bros', 'MGM'],
    answer: 'Warner Bros',
    explanation: 'Harry, Albert, Sam, and Jack Warner founded the studio in 1923, adopting the famous WB shield logo showing their Burbank studio lot photo!',
  },
  {
    no: 36,
    level: 'hard',
    svg: '/logos/cadillac.svg',
    hint: 'American luxury vehicle division of General Motors founded in Detroit in 1902.',
    options: ['Lincoln', 'Cadillac', 'Buick', 'Pontiac'],
    answer: 'Cadillac',
    explanation: 'Named after French explorer Antoine de la Mothe Cadillac, the original 1906 emblem was based on his noble coat of arms family crest!',
  },
  {
    no: 37,
    level: 'hard',
    svg: '/logos/peugeot.svg',
    hint: 'French car brand founded in 1810 as a coffee mill and bicycle manufacturing firm.',
    options: ['Renault', 'Citroën', 'Peugeot', 'Fiat'],
    answer: 'Peugeot',
    explanation: 'Engraver Justin Blazer designed the lion walking on an arrow mark in 1850 to represent the strength and flexibility of Peugeot steel saw blades!',
  },
];

const CONNECTION_PUZZLES = [
  {
    no: 1,
    title: 'Puzzle #1 — Tech & Office Life',
    categories: [
      {
        name: 'TECH GIANTS NAMED AFTER FRUITS OR TREES',
        level: 'yellow',
        words: ['Apple', 'BlackBerry', 'Acorn', 'Cherry'],
      },
      {
        name: 'THINGS YOU CAN "SAVE"',
        level: 'green',
        words: ['File', 'Money', 'Time', 'Face'],
      },
      {
        name: 'WORDS STARTING WITH KEYBOARD KEYS',
        level: 'blue',
        words: ['Altruism', 'Escape', 'Taboo', 'Delete'],
      },
      {
        name: '___ BOARD',
        level: 'purple',
        words: ['Dash', 'Key', 'White', 'Score'],
      },
    ],
  },
  {
    no: 2,
    title: 'Puzzle #2 — Coffee & Productivity',
    categories: [
      {
        name: 'TYPES OF COFFEE DRINKS',
        level: 'yellow',
        words: ['Espresso', 'Latte', 'Mocha', 'Americano'],
      },
      {
        name: 'FUN FRIDAY ACTIVITIES',
        level: 'green',
        words: ['Auction', 'Quiz', 'Trivia', 'Bingo'],
      },
      {
        name: 'THINGS WITH SPRINGS',
        level: 'blue',
        words: ['Mattress', 'Trampoline', 'Watch', 'Season'],
      },
      {
        name: 'WORDS ENDING IN A UNIT OF TIME',
        level: 'purple',
        words: ['Prosecond', 'Hourglass', 'Daybreak', 'Monsoon'],
      },
    ],
  },
  {
    no: 3,
    title: 'Puzzle #3 — Web & Design Systems',
    categories: [
      {
        name: 'POPULAR WEB BROWSERS',
        level: 'yellow',
        words: ['Chrome', 'Safari', 'Firefox', 'Edge'],
      },
      {
        name: 'THINGS YOU CAN "RUN"',
        level: 'green',
        words: ['Code', 'Marathon', 'Meeting', 'Script'],
      },
      {
        name: 'DESIGN & COLOR GEMSTONES',
        level: 'blue',
        words: ['Ruby', 'Emerald', 'Amber', 'Sapphire'],
      },
      {
        name: '___ SHEET',
        level: 'purple',
        words: ['Style', 'Balance', 'Cheat', 'Spread'],
      },
    ],
  },
  {
    no: 4,
    title: 'Puzzle #4 — Software & Infrastructure',
    categories: [
      {
        name: 'POPULAR PROGRAMMING LANGUAGES',
        level: 'yellow',
        words: ['Python', 'Java', 'Rust', 'Swift'],
      },
      {
        name: 'TYPES OF NETWORK CONNECTIONS',
        level: 'green',
        words: ['Fiber', 'Ethernet', 'Bluetooth', 'Wireless'],
      },
      {
        name: 'WORDS THAT MEAN "TO FIX OR REPAIR"',
        level: 'blue',
        words: ['Patch', 'Debug', 'Resolve', 'Overhaul'],
      },
      {
        name: 'CONTAINER TYPES',
        level: 'purple',
        words: ['Docker', 'Freight', 'Cargo', 'Storage'],
      },
    ],
  },
  {
    no: 5,
    title: 'Puzzle #5 — Workplace & Team Culture',
    categories: [
      {
        name: 'POPULAR REACTION EMOJIS',
        level: 'yellow',
        words: ['Fire', 'Rocket', 'Party', 'Tada'],
      },
      {
        name: 'AGILE & SCRUM CEREMONIES',
        level: 'green',
        words: ['Standup', 'Sprint', 'Retro', 'Planning'],
      },
      {
        name: 'WORDS BEFORE "BUG"',
        level: 'blue',
        words: ['Bed', 'Lady', 'Litter', 'Software'],
      },
      {
        name: '___ CODE',
        level: 'purple',
        words: ['Bar', 'Zip', 'Source', 'Moral'],
      },
    ],
  },
];

const STARTING_POINTS = 100; // Productivity Points each member starts the auction with
const CORRECT_VOTE_REWARD = 10; // Quiz points for a correct Myth Buster vote
const LOGO_REWARD = 10; // Points for guessing old logo correctly
const CONNECTION_GROUP_REWARD = 20; // Points for each solved group in Connections

module.exports = {
  AUCTION_ITEMS,
  MYTH_STATEMENTS,
  LOGO_ITEMS,
  CONNECTION_PUZZLES,
  STARTING_POINTS,
  CORRECT_VOTE_REWARD,
  LOGO_REWARD,
  CONNECTION_GROUP_REWARD,
};

